### ISSUE TITLE
browserstack + protractor: Could not find device: Samsung Galaxy S8

### ISSUE THREAD

**Issue by iandeth** [iandeth/trials#1]
# issue

* can't run browserstack automate with device `Samsung Galaxy S8`.
  * browserstack's webdriver throws back `Could not find device` error.

![image](https://user-images.githubusercontent.com/900714/34647871-1ad06dac-f3d2-11e7-9322-c23d60f66aaf.png)

* (but it'll not throw error with other devices like `windows 10 + edge 16`.)

# setup
* using Protractor + Browserstack Automate
  * [followed this guilde](https://www.browserstack.com/automate/protractor)
* I have a Browserstack's Automate-Pro plan, so I'm **not using mobile real-device tesing**.
  * all my config's set to `realMobile: "false"`

![image](https://user-images.githubusercontent.com/900714/34647916-1194b6b6-f3d3-11e7-952a-2736fc138caf.png)

# how to reproduce error
* can reproduce error using [these codes](https://github.com/iandeth/trials/tree/protractor-browserstack-issue/javascript/protractor-20180108/01-basic)
* follow the `setup` instructions on README.md first
* then run this command:

```sh
$ ./node_modules/protractor/bin/protractor conf-browserstack.js

(node:70396) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[17:34:25] I/launcher - Running 1 instances of WebDriver
[17:34:25] I/hosted - Using the selenium server at http://hub-cloud.browserstack.com/wd/hub
[17:34:27] E/launcher - Could not find device: Samsung Galaxy S8
...
```

* the capability config is like this, which I copy/pasted from [this page](https://www.browserstack.com/automate/node#setting-os-and-browser)

```js
  'multiCapabilities': [{
    'browserName' : 'android',
    'device' : 'Samsung Galaxy S8',
    'realMobile' : 'false',
    'os_version' : '7.0'
  }],
```

<img width="300" alt="selenium_testing_with_node_js___browserstack" src="https://user-images.githubusercontent.com/900714/34648093-6c70d058-f3d6-11e7-8d42-a89addabe33d.png">

* i've also tried config code on [this page](https://www.browserstack.com/automate/protractor) too, but error ditto.

<img width="300" alt="browserstack_node_js_protractor_documentation" src="https://user-images.githubusercontent.com/900714/34648083-4d5a19a4-f3d6-11e7-91d3-6199b994f40c.png">

# no-error using other devices

* with the same setup/code, when I configure to run desktop browsers and old android os', it runs fine as expected

## eg. windows edge

```js
  'multiCapabilities': [{
    "os": "Windows",
    "os_version": "10",
    "browserName": "edge",
    "browser_version": "16.0"
  }],
```

<img src="https://user-images.githubusercontent.com/900714/34648010-d8269a50-f3d4-11e7-879c-abf9fe8626d6.png" width=400/>

## eg. android galaxy s3

```js
  'multiCapabilities': [{
    'browserName' : 'android',
    'platform' : 'ANDROID',
    'device' : 'Samsung Galaxy S3'
  }],
```

<img src="https://user-images.githubusercontent.com/900714/34648044-5264e768-f3d5-11e7-81fa-671924433afe.png" width=400/>

![image](https://user-images.githubusercontent.com/900714/34648042-480cd578-f3d5-11e7-9642-0ba2a8ff0095.png)

# conclude

* so my guess is: the cause is at capability config.
* can browserstack support team tell me **the correct config for galaxy S8** (and also for iPhone 8) ?

**Comment by iandeth** [comment]
reply from browserstack support team:

> The device Samsung Galaxy S8 is only available as a real mobile device on BrowserStack Automate. Please refer to the list of supported devices for Automate here. The device marked with the blue phone icon are real devices. You need to include the capability "realMobile" = true in your test scripts in order to run tests on these devices.
> 
> I checked the issue link you shared and as clearly mentioned in the screenshots attached you need to pass the capability "realMobile" = true. Please make the changes and rerun the test.
> 
> Let me know how things go.

Now I understand the feature.
I mis-understood that 'real mobile' feature is an add-on, and there's always a non-real-device version of it too.

**Comment by iandeth** [comment]
# Additional two questions to understand the features clearly

## Q1. There's some simulator mobile devices available that's not on [support browser list](https://www.browserstack.com/list-of-browsers-and-platforms?product=automate).  Are they valid for my plan?

### What I want to know

There's a device that supposed to support `real-device` only, but still could run in simulator mode.

* Is this a supported service under our subscription plan? (can we keep using it?)
* If not, what's the expected timeline before those devices no longer be available?  (=how quickly do we need to purchase Automate mobile plan?)

### Example: iPhone 7 Plus

<img width="600" src="https://user-images.githubusercontent.com/900714/34705789-64d8339c-f546-11e7-98fe-40e2a5ba1589.png"/>

but with config like this, I'm able to run on simulator version of device:

```js
"os": "ios",
"os_version": "10.3",
"device": "iPhone 7 Plus",
"real_mobile": false    // make this false
```

result:

<img width="1003" alt="browserstack_automate___session_information_" src="https://user-images.githubusercontent.com/900714/34706845-56375186-f54d-11e7-9701-8e79abdbe253.png">


## Q2. What is the free-of-use limit on real device feature, without the `Automate Mobile` plan?

### What I want to know

I'm able to run `realDevice:true` tests with javascript testing (without automate mobile plan).
But with selenium testing, I can't (plan upgrade required).

1. what is the usage limit for javascript testing?
    - is it 100 min on javascript testing, separate from 100 min for selenium testing?
2. if there's a limit, then how can I check minutes left I have?
3. or should we expect that we **should not be able** to run `realDevice:true` javascript testing with our subscription plan?

### Our subscription plan
- We're currently on `Automate Pro` plan
  - slightly a diversion plan of it, we received [this offer](https://user-images.githubusercontent.com/900714/34700287-c47d271a-f525-11e7-8e25-8080f236f10c.png).
- so with real-device testing, I understand there is a [usage limit](https://www.browserstack.com/question/540).

### Situation
when I try to run `realMobile: true` devices...

#### With automate: selenium testing, I get `Your free access to test on real device has expired` as expected

![image](https://user-images.githubusercontent.com/900714/34700384-39dfbff4-f526-11e7-857b-86dc7118eb2a.png)

== I need to subscribe `Automate Pro` plan for it. I get this.

#### With automate: javascript testing, I can still run real-device tests without errors

differ from selenium testing above, i don't get any `Your free access to test on real device has expired` error, but with success:

<img width="500" alt="browserstack_automate___session_information_" src="https://user-images.githubusercontent.com/900714/34700675-96c48b5e-f527-11e7-90c0-c4e72504385f.png">

### So my assumption is

* there's a different usage limit between selenium and javascript testing.
  * I've used up my selenium testing limit
  * but there's still time left on javascript testing.

**Comment by iandeth** [comment]
reply from browserstack support team:

> Please find answers to your queries below:
> 
> 1) We do not provide the same device as both simulator and real mobile device for Selenium testing. I understand you are seeing this behaviour only while running JS tests (JavaScript testing). Real iOS devices were recently added to JS testing. The same device simulator/emulator will soon be removed since we plan to completely switch to real mobile devices on BrowserStack. 
> 
> 2) I have confirmed this with the Engineering team and you should have access to real mobile devices on both Selenium and JS testing. There is no limit on the testing minutes at the moment. We plan to completely remove mobile emulators starting March 2018. If you continue to renew your current plan (upto May 2018) you will have access to real mobile devices. Post that you will have to explicitly upgrade to a new plan that allows access to real mobile devices on Automate.
> 
> Let me know if you have any further queries.
> Regards,
> Ashwin Gonsalves
> BrowserStack Support

**Comment by ngraf** [comment]
I came back here in 2023 because I was looking for an answer why I can't find any simulator ("realMobile": "false") setup anymore that works.
I had today contact with Browserstack and their answer was "we **only provide real devices** for the test execution." in September 2023.

Looks like the sentence "The same device simulator/emulator will soon be removed since we plan to completely switch to real mobile devices on BrowserStack." in 2018 became reality by now.
